### ISSUE TITLE
Use minio as a target for the traffic generated

### ISSUE THREAD

**Issue by markband** [filetrust/k8-traffic-generator#18]
Use minio as a target for the traffic generated

**Comment by faisaladnanpeltops** [comment]
Hi @markband , let's work together on this.

I've prepared a minio PoC and any application can upload files to minio using S3 API. 
What do you need to start with this task?

**Comment by xuxant** [comment]
Can you be more descriptive about how do you want me to proceed? Do we create the load to the minio by doing get and put request to it?

**Comment by faisaladnanpeltops** [comment]
@xuxant , for starters,
- try the Minio PoC explained here on local machine.
https://github.com/filetrust/k8-glasswall-rebuild/tree/master/upwork-devs/faisal-adnan
- create a python function to upload and download a file

**Comment by markband** [comment]
[from Slack Channel] This is about:
Instead of the target being a website like the GW website, the target is the web UI of minio
Start a pod with minio
Add a number of files to it
Use browser automation (or direct requests if possible) to download those files
Once the above is done, add support for using a separate minio pod to store the files downloaded
Does this make sense?

New :task:  create architecture diagram and sequence diagram for this workflow

**Comment by pranaysahith** [comment]
Assigning to @xuxant as he already created PR #33

**Comment by Rajwinder1985** [comment]
Hi, @markband,
 
This is about:
Instead of the target being a website like the GW website, the target is the web UI of minio
Start a pod with minio
Add a number of files to it
Use browser automation (or direct requests if possible) to download those files
Once the above is done, add support for using a separate minio pod to store the files downloaded
Does this make sense?

I need to discuss
===========
1. What kind of WebUI of Minio do you want to configure?
2. First, I need to configure the POD with Minio, or Will you provide the access of Environment for the K8s like AWS?
3. For Browser automation, I am going to code for the direct requests. Is this ok?
